# For more info on HTTP files go to https://aka.ms/vs/httpfile
@base=https://localhost:7410

GET {{base}}/wiki?keyword=ブッキー


###
POST {{base}}/target
Content-Type: application/json
"キュアパイン"

###

POST {{base}}/question
Content-Type: application/json
"人ですか？"

###

POST {{base}}/question
Content-Type: application/json
"男性？"

###

POST {{base}}/question
Content-Type: application/json
"子供ですか？"

###

POST {{base}}/question
Content-Type: application/json
"アニメのキャラ？"

###

POST {{base}}/question
Content-Type: application/json
"プリキュアの登場人物？"

###

POST {{base}}/question
Content-Type: application/json
"中学2年生？"

###

POST {{base}}/question
Content-Type: application/json
"黄色がテーマカラー？"

###

POST {{base}}/answer
Content-Type: application/json
"キュアパイン"

###

POST {{base}}/answer
Content-Type: application/json
"キュアレモネード"

###

POST {{base}}/answer
Content-Type: application/json
"キュアサンシャイン"

###

POST {{base}}/answer
Content-Type: application/json
"ブッキー"

###

POST {{base}}/answer
Content-Type: application/json
"山吹祈里"
