# For more info on HTTP files go to https://aka.ms/vs/httpfile
@base=https://localhost:7410/api

GET {{base}}/wiki?keyword=ブッキー

###

GET {{base}}/search?keyword=ブッキー

###
POST {{base}}/target
Content-Type: application/json

"ミッキーマウス"

###

POST {{base}}/question
Content-Type: application/json

"人ですか？"

###

POST {{base}}/question
Content-Type: application/json

"場所ですか？"

###

POST {{base}}/question
Content-Type: application/json

"物ですか？"

###

POST {{base}}/question
Content-Type: application/json

"食べ物？"

###

POST {{base}}/question
Content-Type: application/json

"アニメのキャラ？"

###

POST {{base}}/question
Content-Type: application/json

"ディズニーに関係ある？"

###

POST {{base}}/question
Content-Type: application/json

"1950年以降の作品？"

###

POST {{base}}/answer
Content-Type: application/json

"ミッキーマウス"

###

POST {{base}}/answer
Content-Type: application/json

"ミニーマウス"

###

POST {{base}}/answer
Content-Type: application/json

"キュアサンシャイン"

###

POST {{base}}/answer
Content-Type: application/json

"ブッキー"

###

POST {{base}}/answer
Content-Type: application/json

"山吹祈里"

###

GET {{base}}/history

###

GET {{base}}/history/internal

### 

GET {{base}}/trends/InterestOverTime

### 

GET {{base}}/trends/TrendingSearches

### 

GET {{base}}/trends/RealtimeSearches

### 

GET {{base}}/trends/TopCharts

### 

GET {{base}}/trends/TodaySearches

### 

GET {{base}}/trends/RelatedQueries

###

GET {{base}}/session

### プレイヤー・トピック登録

POST {{base}}/regist
Content-Type: application/json

{
    "name": "Freesia",
    "topic": "ミッキーマウス"
}

### ラウンドスタート

POST {{base}}/start
